/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goodfit;

import org.jdesktop.application.Action;

/**
 *
 * @author David Alarcon
 */
public class entrenamiento extends javax.swing.JDialog {

    /**
     * Creates new form clientes
     */
    public entrenamiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblEntrenamiento = new javax.swing.JLabel();
        txtEntrentamiento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        rdoMuscular = new javax.swing.JRadioButton();
        rdoFuncional = new javax.swing.JRadioButton();
        rdoCrossfit = new javax.swing.JRadioButton();
        rdoFuerza = new javax.swing.JRadioButton();
        rdoRunning = new javax.swing.JRadioButton();
        rdoFisico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(goodfit.GoodFitApp.class).getContext().getResourceMap(entrenamiento.class);
        lblCodigo.setText(resourceMap.getString("lblCodigo.text")); // NOI18N
        lblCodigo.setName("lblCodigo"); // NOI18N

        txtCodigo.setText(resourceMap.getString("txtCodigo.text")); // NOI18N
        txtCodigo.setName("txtCodigo"); // NOI18N

        lblEntrenamiento.setText(resourceMap.getString("lblEntrenamiento.text")); // NOI18N
        lblEntrenamiento.setName("lblEntrenamiento"); // NOI18N

        txtEntrentamiento.setName("txtEntrentamiento"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        lblTipo.setText(resourceMap.getString("lblTipo.text")); // NOI18N
        lblTipo.setName("lblTipo"); // NOI18N

        grpTipo.add(rdoMuscular);
        rdoMuscular.setText(resourceMap.getString("rdoMuscular.text")); // NOI18N
        rdoMuscular.setName("rdoMuscular"); // NOI18N

        grpTipo.add(rdoFuncional);
        rdoFuncional.setText(resourceMap.getString("rdoFuncional.text")); // NOI18N
        rdoFuncional.setName("rdoFuncional"); // NOI18N

        grpTipo.add(rdoCrossfit);
        rdoCrossfit.setText(resourceMap.getString("rdoCrossfit.text")); // NOI18N
        rdoCrossfit.setName("rdoCrossfit"); // NOI18N

        grpTipo.add(rdoFuerza);
        rdoFuerza.setText(resourceMap.getString("rdoFuerza.text")); // NOI18N
        rdoFuerza.setName("rdoFuerza"); // NOI18N

        grpTipo.add(rdoRunning);
        rdoRunning.setText(resourceMap.getString("rdoRunning.text")); // NOI18N
        rdoRunning.setName("rdoRunning"); // NOI18N

        grpTipo.add(rdoFisico);
        rdoFisico.setText(resourceMap.getString("rdoFisico.text")); // NOI18N
        rdoFisico.setName("rdoFisico"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rdoMuscular)
                        .addGap(18, 18, 18)
                        .addComponent(rdoFuncional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoCrossfit)
                        .addGap(63, 63, 63)
                        .addComponent(rdoFuerza)
                        .addGap(18, 18, 18)
                        .addComponent(rdoRunning)
                        .addGap(37, 37, 37)
                        .addComponent(rdoFisico)
                        .addGap(0, 60, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMuscular)
                    .addComponent(rdoFuncional)
                    .addComponent(rdoCrossfit)
                    .addComponent(rdoFuerza)
                    .addComponent(rdoRunning)
                    .addComponent(rdoFisico))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEntrenamiento)
                        .addGap(39, 39, 39)
                        .addComponent(txtEntrentamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(39, 39, 39)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(428, 428, 428))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrentamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntrenamiento))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
                // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (!Character.isAlphabetic(car) && !Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String codigo = this.txtCodigo.getText();
        if(codigo.length()>5)
            evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entrenamiento dialog = new entrenamiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void marcarCasillas() {
        int item = cmbUbicacion.getSelectedIndex();   
        if(item==1){
         chbBancos.setEnabled(true); 
         chbBicicleta.setEnabled(true);
         chbCinta.setEnabled(true);
         chbMultifuncion.setEnabled(true);
         chbPalancas.setEnabled(true);
         chbPlacas.setEnabled(true);
        } else if(item==2){
         chbBancos.setEnabled(false); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(false);
         chbPalancas.setEnabled(true);
         chbPlacas.setEnabled(true);
        }
  
        else if(item==3){
         chbBancos.setEnabled(true); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(true);
         chbPalancas.setEnabled(false);
         chbPlacas.setEnabled(false);    
        } else{
         chbBancos.setEnabled(false); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(false);
         chbPalancas.setEnabled(false);
         chbPlacas.setEnabled(false);    
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEntrenamiento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rdoCrossfit;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoFuerza;
    private javax.swing.JRadioButton rdoFuncional;
    private javax.swing.JRadioButton rdoMuscular;
    private javax.swing.JRadioButton rdoRunning;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEntrentamiento;
    // End of variables declaration//GEN-END:variables
}
