/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goodfit;

import org.jdesktop.application.Action;

/**
 *
 * @author David Alarcon
 */
public class entrenamiento extends javax.swing.JDialog {

    /**
     * Creates new form clientes
     */
    public entrenamiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblEntrenamiento = new javax.swing.JLabel();
        txtEntrenamiento = new javax.swing.JTextField();
        jPanelTipo = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        rdoMuscular = new javax.swing.JRadioButton();
        rdoFuncional = new javax.swing.JRadioButton();
        rdoCrossfit = new javax.swing.JRadioButton();
        rdoFuerza = new javax.swing.JRadioButton();
        rdoRunning = new javax.swing.JRadioButton();
        rdoFisico = new javax.swing.JRadioButton();
        cmbArea = new javax.swing.JComboBox();
        lblArea = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        lblFecha = new javax.swing.JLabel();
        lblEntrenador = new javax.swing.JLabel();
        txtEntrenador = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblEuro = new javax.swing.JLabel();
        jPanelUbicacion = new javax.swing.JPanel();
        lblUbicacion = new javax.swing.JLabel();
        cmbUbicacion = new javax.swing.JComboBox();
        chbBancos = new javax.swing.JCheckBox();
        chbBicicleta = new javax.swing.JCheckBox();
        chbCinta = new javax.swing.JCheckBox();
        chbMultifuncion = new javax.swing.JCheckBox();
        chbPalancas = new javax.swing.JCheckBox();
        chbPlacas = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(goodfit.GoodFitApp.class).getContext().getResourceMap(entrenamiento.class);
        lblCodigo.setText(resourceMap.getString("lblCodigo.text")); // NOI18N
        lblCodigo.setName("lblCodigo"); // NOI18N

        txtCodigo.setText(resourceMap.getString("txtCodigo.text")); // NOI18N
        txtCodigo.setName("txtCodigo"); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        lblEntrenamiento.setText(resourceMap.getString("lblEntrenamiento.text")); // NOI18N
        lblEntrenamiento.setName("lblEntrenamiento"); // NOI18N

        txtEntrenamiento.setName("txtEntrenamiento"); // NOI18N
        txtEntrenamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntrenamientoKeyTyped(evt);
            }
        });

        jPanelTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelTipo.setName("jPanelTipo"); // NOI18N

        lblTipo.setText(resourceMap.getString("lblTipo.text")); // NOI18N
        lblTipo.setName("lblTipo"); // NOI18N

        grpTipo.add(rdoMuscular);
        rdoMuscular.setText(resourceMap.getString("rdoMuscular.text")); // NOI18N
        rdoMuscular.setName("rdoMuscular"); // NOI18N
        rdoMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMuscularActionPerformed(evt);
            }
        });

        grpTipo.add(rdoFuncional);
        rdoFuncional.setText(resourceMap.getString("rdoFuncional.text")); // NOI18N
        rdoFuncional.setName("rdoFuncional"); // NOI18N
        rdoFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFuncionalActionPerformed(evt);
            }
        });

        grpTipo.add(rdoCrossfit);
        rdoCrossfit.setText(resourceMap.getString("rdoCrossfit.text")); // NOI18N
        rdoCrossfit.setName("rdoCrossfit"); // NOI18N
        rdoCrossfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCrossfitActionPerformed(evt);
            }
        });

        grpTipo.add(rdoFuerza);
        rdoFuerza.setText(resourceMap.getString("rdoFuerza.text")); // NOI18N
        rdoFuerza.setName("rdoFuerza"); // NOI18N
        rdoFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFuerzaActionPerformed(evt);
            }
        });

        grpTipo.add(rdoRunning);
        rdoRunning.setText(resourceMap.getString("rdoRunning.text")); // NOI18N
        rdoRunning.setName("rdoRunning"); // NOI18N
        rdoRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRunningActionPerformed(evt);
            }
        });

        grpTipo.add(rdoFisico);
        rdoFisico.setText(resourceMap.getString("rdoFisico.text")); // NOI18N
        rdoFisico.setName("rdoFisico"); // NOI18N
        rdoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFisicoActionPerformed(evt);
            }
        });

        cmbArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Tren Superior", "Tren Inferior", "Tronco", "Core" }));
        cmbArea.setEnabled(false);
        cmbArea.setName("cmbArea"); // NOI18N

        lblArea.setText(resourceMap.getString("lblArea.text")); // NOI18N
        lblArea.setName("lblArea"); // NOI18N

        javax.swing.GroupLayout jPanelTipoLayout = new javax.swing.GroupLayout(jPanelTipo);
        jPanelTipo.setLayout(jPanelTipoLayout);
        jPanelTipoLayout.setHorizontalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTipoLayout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTipoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTipoLayout.createSequentialGroup()
                                .addComponent(rdoMuscular)
                                .addGap(18, 18, 18)
                                .addComponent(rdoFisico)
                                .addGap(51, 51, 51)
                                .addComponent(rdoCrossfit)
                                .addGap(63, 63, 63)
                                .addComponent(rdoFuerza)
                                .addGap(18, 18, 18)
                                .addComponent(rdoRunning)
                                .addGap(18, 18, 18)
                                .addComponent(rdoFuncional)
                                .addGap(0, 41, Short.MAX_VALUE))
                            .addGroup(jPanelTipoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblArea)
                                .addGap(33, 33, 33)
                                .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanelTipoLayout.setVerticalGroup(
            jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoLayout.createSequentialGroup()
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMuscular)
                    .addComponent(rdoCrossfit)
                    .addComponent(rdoFuerza)
                    .addComponent(rdoRunning)
                    .addComponent(rdoFisico)
                    .addComponent(rdoFuncional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbArea)
                    .addComponent(lblArea))
                .addContainerGap())
        );

        spnFecha.setModel(new javax.swing.SpinnerDateModel());
        spnFecha.setEditor(new javax.swing.JSpinner.DateEditor(spnFecha, "dd/MM/yyyy"));
        spnFecha.setName("spnFecha"); // NOI18N

        lblFecha.setText(resourceMap.getString("lblFecha.text")); // NOI18N
        lblFecha.setName("lblFecha"); // NOI18N

        lblEntrenador.setText(resourceMap.getString("lblEntrenador.text")); // NOI18N
        lblEntrenador.setName("lblEntrenador"); // NOI18N

        txtEntrenador.setText(resourceMap.getString("txtEntrenador.text")); // NOI18N
        txtEntrenador.setName("txtEntrenador"); // NOI18N
        txtEntrenador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntrenadorKeyTyped(evt);
            }
        });

        lblTelefono.setText(resourceMap.getString("lblTelefono.text")); // NOI18N
        lblTelefono.setName("lblTelefono"); // NOI18N

        txtTelefono.setText(resourceMap.getString("txtTelefono.text")); // NOI18N
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        lblPrecio.setText(resourceMap.getString("lblPrecio.text")); // NOI18N
        lblPrecio.setName("lblPrecio"); // NOI18N

        txtPrecio.setText(resourceMap.getString("txtPrecio.text")); // NOI18N
        txtPrecio.setName("txtPrecio"); // NOI18N
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        lblEuro.setText(resourceMap.getString("lblEuro.text")); // NOI18N
        lblEuro.setName("lblEuro"); // NOI18N

        jPanelUbicacion.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelUbicacion.setName("jPanelUbicacion"); // NOI18N

        lblUbicacion.setText(resourceMap.getString("lblUbicacion.text")); // NOI18N
        lblUbicacion.setName("lblUbicacion"); // NOI18N

        cmbUbicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sala Cross", "Sala Fitness", "Sala Musculación" }));
        cmbUbicacion.setName("cmbUbicacion"); // NOI18N
        cmbUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUbicacionActionPerformed(evt);
            }
        });

        chbBancos.setText(resourceMap.getString("chbBancos.text")); // NOI18N
        chbBancos.setEnabled(false);
        chbBancos.setName("chbBancos"); // NOI18N

        chbBicicleta.setText(resourceMap.getString("chbBicicleta.text")); // NOI18N
        chbBicicleta.setEnabled(false);
        chbBicicleta.setName("chbBicicleta"); // NOI18N

        chbCinta.setText(resourceMap.getString("chbCinta.text")); // NOI18N
        chbCinta.setEnabled(false);
        chbCinta.setName("chbCinta"); // NOI18N

        chbMultifuncion.setText(resourceMap.getString("chbMultifuncion.text")); // NOI18N
        chbMultifuncion.setEnabled(false);
        chbMultifuncion.setName("chbMultifuncion"); // NOI18N

        chbPalancas.setText(resourceMap.getString("chbPalancas.text")); // NOI18N
        chbPalancas.setEnabled(false);
        chbPalancas.setName("chbPalancas"); // NOI18N

        chbPlacas.setText(resourceMap.getString("chbPlacas.text")); // NOI18N
        chbPlacas.setEnabled(false);
        chbPlacas.setName("chbPlacas"); // NOI18N

        javax.swing.GroupLayout jPanelUbicacionLayout = new javax.swing.GroupLayout(jPanelUbicacion);
        jPanelUbicacion.setLayout(jPanelUbicacionLayout);
        jPanelUbicacionLayout.setHorizontalGroup(
            jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblUbicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                                .addComponent(chbBancos)
                                .addGap(71, 71, 71)
                                .addComponent(chbBicicleta))
                            .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                                .addComponent(chbMultifuncion)
                                .addGap(18, 18, 18)
                                .addComponent(chbPalancas)))
                        .addGap(69, 69, 69)
                        .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbCinta)
                            .addComponent(chbPlacas))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanelUbicacionLayout.setVerticalGroup(
            jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbicacion)
                    .addComponent(cmbUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbBancos)
                    .addComponent(chbBicicleta)
                    .addComponent(chbCinta))
                .addGap(38, 38, 38)
                .addGroup(jPanelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbMultifuncion)
                    .addComponent(chbPalancas)
                    .addComponent(chbPlacas))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnCancelar.setText(resourceMap.getString("btnCancelar.text")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N

        btnAceptar.setText(resourceMap.getString("btnAceptar.text")); // NOI18N
        btnAceptar.setName("btnAceptar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEntrenamiento)
                        .addGap(39, 39, 39)
                        .addComponent(txtEntrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(39, 39, 39)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(428, 428, 428))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblEntrenador)
                                .addGap(18, 18, 18)
                                .addComponent(txtEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEuro))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addComponent(btnAceptar))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntrenamiento))
                .addGap(29, 29, 29)
                .addComponent(jPanelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrenador)
                    .addComponent(txtEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEuro))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(68, 68, 68)
                        .addComponent(btnAceptar)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
                // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (!Character.isAlphabetic(car) && !Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String codigo = this.txtCodigo.getText();
        if(codigo.length()>=5)
            evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtEntrenamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntrenamientoKeyTyped
        // TODO add your handling code here:
      char car = evt.getKeyChar();
        if (!Character.isAlphabetic(car) && !Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String ent = this.txtEntrenamiento.getText();
        if(ent.length()>=10)
            evt.consume();
    }//GEN-LAST:event_txtEntrenamientoKeyTyped

    private void txtEntrenadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntrenadorKeyTyped
        // TODO add your handling code here:
       char car = evt.getKeyChar();
        if (!Character.isAlphabetic(car) && !Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String codigo = this.txtEntrenador.getText();
        if(codigo.length()>=10)
            evt.consume();
    }//GEN-LAST:event_txtEntrenadorKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
               char car = evt.getKeyChar();
        if (!Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String tel = this.txtTelefono.getText();
        if(tel.length()>=9)
            evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
          char car = evt.getKeyChar();
          if (!Character.isDigit(car)){
            evt.consume();
             //System.out.println("No es un número o una letra");
        }
        String bono = this.txtPrecio.getText();
        //char cent = bono.charAt(0);
         if(bono.length()>=3)
            evt.consume();
         //else if (bono.length()==3 && cent>'2')
           //  evt.consume();
        //int bononum = Integer.parseInt(bono);	
        //if(bononum>200)
          //  evt.consume();
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        // TODO add your handling code here:
               String bono = this.txtPrecio.getText();
    
        int bononum = Integer.parseInt(bono);	
        if(bononum>200)
          this.txtPrecio.setText("");
    }//GEN-LAST:event_txtPrecioFocusLost

    private void cmbUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUbicacionActionPerformed
        // TODO add your handling code here:
       
       int item = cmbUbicacion.getSelectedIndex();   
        if(item==1){
         chbBancos.setEnabled(true); 
         chbBicicleta.setEnabled(true);
         chbCinta.setEnabled(true);
         chbMultifuncion.setEnabled(true);
         chbPalancas.setEnabled(true);
         chbPlacas.setEnabled(true);
        } else if(item==2){
         chbBancos.setEnabled(false); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(false);
         chbPalancas.setEnabled(true);
         chbPlacas.setEnabled(true);
        }
  
        else if(item==3){
         chbBancos.setEnabled(true); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(true);
         chbPalancas.setEnabled(false);
         chbPlacas.setEnabled(false);    
        } else{
         chbBancos.setEnabled(false); 
         chbBicicleta.setEnabled(false);
         chbCinta.setEnabled(false);
         chbMultifuncion.setEnabled(false);
         chbPalancas.setEnabled(false);
         chbPlacas.setEnabled(false);    
        }
        
    }//GEN-LAST:event_cmbUbicacionActionPerformed

    private void rdoMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMuscularActionPerformed
           if(rdoMuscular.isSelected())
               cmbArea.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_rdoMuscularActionPerformed

    private void rdoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFisicoActionPerformed
        // TODO add your handling code here:
               if(rdoFisico.isSelected())
               cmbArea.setEnabled(true);
    }//GEN-LAST:event_rdoFisicoActionPerformed

    private void rdoCrossfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCrossfitActionPerformed
        // TODO add your handling code here:
            if(rdoCrossfit.isSelected())
               cmbArea.setEnabled(false);
    }//GEN-LAST:event_rdoCrossfitActionPerformed

    private void rdoFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFuerzaActionPerformed
             if(rdoFuerza.isSelected())
               cmbArea.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_rdoFuerzaActionPerformed

    private void rdoRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRunningActionPerformed
                    if(rdoRunning.isSelected())
               cmbArea.setEnabled(false); // TODO add your handling code here:
    }//GEN-LAST:event_rdoRunningActionPerformed

    private void rdoFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFuncionalActionPerformed
             if(rdoFuncional.isSelected())
               cmbArea.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFuncionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entrenamiento dialog = new entrenamiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void marcarCasillas() {
        int item = cmbUbicacion.getSelectedIndex();   
        if(item==1){
         chbBancos.setEnabled(true);
         chbBancos.setSelected(false);
         chbBicicleta.setEnabled(true);
         chbBicicleta.setSelected(false);
         chbCinta.setEnabled(true);
         chbCinta.setSelected(false);
         chbMultifuncion.setEnabled(true);
         chbMultifuncion.setSelected(false);
         chbPalancas.setEnabled(true);
         chbPalancas.setSelected(false);
         chbPlacas.setEnabled(true);
         chbPlacas.setSelected(false);
        } else if(item==2){
         chbBancos.setEnabled(false); 
         chbBancos.setSelected(false);
         chbBicicleta.setEnabled(false);
         chbBicicleta.setSelected(false);
         chbCinta.setEnabled(false);
         chbCinta.setSelected(false);
         chbMultifuncion.setEnabled(false);
         chbMultifuncion.setSelected(false);
         chbPalancas.setEnabled(true);
         chbPalancas.setSelected(false);
         chbPlacas.setEnabled(true);
         chbPlacas.setSelected(false);
        }
  
        else if(item==3){
         chbBancos.setEnabled(true); 
         chbBancos.setSelected(false);
         chbBicicleta.setEnabled(false);
         chbBicicleta.setSelected(false);
         chbCinta.setEnabled(false);
         chbCinta.setSelected(false);
         chbMultifuncion.setEnabled(false);
         chbMultifuncion.setSelected(false);
         chbPalancas.setEnabled(false);
         chbPalancas.setSelected(false);
         chbPlacas.setEnabled(true);
         chbPlacas.setSelected(false);  
        } else{
         chbBancos.setEnabled(false); 
         chbBancos.setSelected(false);
         chbBicicleta.setEnabled(false);
         chbBicicleta.setSelected(false);
         chbCinta.setEnabled(false);
         chbCinta.setSelected(false);
         chbMultifuncion.setEnabled(false);
         chbMultifuncion.setSelected(false);
         chbPalancas.setEnabled(false);
         chbPalancas.setSelected(false);
         chbPlacas.setEnabled(false);
         chbPlacas.setSelected(false) ;   
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chbBancos;
    private javax.swing.JCheckBox chbBicicleta;
    private javax.swing.JCheckBox chbCinta;
    private javax.swing.JCheckBox chbMultifuncion;
    private javax.swing.JCheckBox chbPalancas;
    private javax.swing.JCheckBox chbPlacas;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbUbicacion;
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JPanel jPanelTipo;
    private javax.swing.JPanel jPanelUbicacion;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEntrenador;
    private javax.swing.JLabel lblEntrenamiento;
    private javax.swing.JLabel lblEuro;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JRadioButton rdoCrossfit;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoFuerza;
    private javax.swing.JRadioButton rdoFuncional;
    private javax.swing.JRadioButton rdoMuscular;
    private javax.swing.JRadioButton rdoRunning;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEntrenador;
    private javax.swing.JTextField txtEntrenamiento;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
